### ISSUE TITLE
Roadmap to release

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/lmoments3#3]
- [ ] Have some pre-commit tools to ensure code quality
- [ ] Have at least one CI test build
- [ ] Take over ReadTheDocs
- [ ] Update packaging
    - [ ] Put a lower pin to `scipy` and `numpy`, if needed
- [ ] Add pinned issue in main repo redirecting people over here
- [ ] Add mention of this fork in the main repo's Readme
- [ ] Add a conda-forge package

I guess most of there are optional, but why not. 

I suggest we try to keep it a simple as possible, but with enough automation and safeguards so that we don't have to put too much time in it.
